name 'elasticbeat'
maintainer 'Nik Ogura'
maintainer_email 'nik.ogura@gmail.com'
license 'MIT'
description 'Installs/Configures Elastic Beats via Systemd Drop-In'
long_description 'Installs/Configures Elastic Beats via Systemd Drop-In'
version '1.0.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/nikogura/elasticbeat-cookbook/issues'
source_url 'https://github.com/nikogura/elasticbeat-cookbook'
supports 'ubuntu'
